baseURL = "https://prototype-kxd7.onrender.com"
languageCode = "en-us"
title = "billal izzamuddin malik"
theme = "m10c"
[params] 
    author = "billal"
    description = "www.gunadarma.ac.id"
    

[[params.social]]
  name = "instagram"
  url = "https://www.instagram.com/izmdnbillal/"
